# Theme dùng cho site
theme = "hugo-theme-learn"

# BaseURL: để "/" cho Netlify, khi build GitHub Pages sẽ set qua lệnh build
baseURL = "/"

# Dùng URL tương đối để tránh lỗi CSS/JS khi đổi domain
relativeURLs = true
canonifyURLs = true

# Output formats
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  # Màu theme (red, blue, green, workshop...)
  themeVariant = "workshop"
  # GitHub repo link
  editURL = ""
  description = ""
  author = "baoanh25100@gmail.com"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false

[Languages]
[Languages.en]
title = "AWS System Manager"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> AWS Study Group"
identifier = "AWS Study Group FB"
url = "https://www.facebook.com/groups/awsstudygroupfcj/"
weight = 20

[Languages.vi]
title = "AWS System Manager"
weight = 2
languageName = "Tiếng Việt"

[[Languages.vi.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> AWS Study Group"
identifier = "AWS Study Group FB"
url = "https://www.facebook.com/groups/awsstudygroupfcj/"
weight = 20
